### PR TITLE
Fix last_github_update in projects

### LINKED ISSUE #1506: Wrong date displayed for project Last Update
Line should be:
last_github_update: client.repo(github_url(project)).pushed_at)

### PR DESCRIPTION
**Pull request by mattlindsey**
fixes #1506

### CODE REVIEW

File: app/jobs/github_commits_job.rb [hunk 1]
```diff
@@ -8,6 +8,7 @@ def run
       begin
         update_total_commit_count_for(project)
         update_user_commit_counts_for(project)
+        update_last_pushed_dt_for(project)
```
Comment (tansaku) [inline app/jobs/github_commits_job.rb]: so perhaps we want to have these in separate rescues so one failure doesn't block the others?

File: app/jobs/github_commits_job.rb [hunk 2]
```diff
@@ -8,6 +8,7 @@ def run
...
       rescue Exception
```
Comment (tansaku) [inline app/jobs/github_commits_job.rb]: And we might want to replace this Exception with StandardError: https://robots.thoughtbot.com/rescue-standarderror-not-exception I know you didn't introduce this, but a great time to fix it perhaps ...
