### PR TITLE
adjusting subscription <-> user relation to has_many to better reflect reality

### LINKED ISSUE #1429: UpgradeUserToPremium is creating Subscription rather than upgrading
also it can be passed a parameter for the subscription type.

Really it should be called ChangeOrCreateUserSubscription and adjusted to take into account existing subscriptions so users don't end up with multiple subscriptions of same type, or multiple at different levels since the superior subscriptions encompass the lower ones.

### LINKED ISSUE #1808: Can we get good reporting for 500 errors?
I just got a 500 error going to an event page.  I just had a quick look in the logs and see this:

```
2017-09-05T11:00:41.951305+00:00 app[web.1]: source=rack-timeout id=0d0de188-feb9-465b-b19a-25b81c4a2f54 wait=8ms timeout=20000ms state=ready
2017-09-05T11:00:41.955638+00:00 app[web.1]: Started GET "/events/2" for 86.145.233.255 at 2017-09-05 11:00:41 +0000
2017-09-05T11:00:41.961437+00:00 app[web.1]: Processing by EventsController#show as HTML
2017-09-05T11:00:41.961490+00:00 app[web.1]:   Parameters: {"id"=>"2"}
2017-09-05T11:00:42.454497+00:00 app[web.1]: source=rack-timeout id=f39625fa-89af-4093-8c97-d249748cf412 wait=109ms timeout=20000ms state=ready
2017-09-05T11:00:42.651980+00:00 app[web.1]: Started GET "/events/2" for 86.145.233.255 at 2017-09-05 11:00:42 +0000
2017-09-05T11:00:42.754025+00:00 app[web.1]: Processing by EventsController#show as HTML
2017-09-05T11:00:42.754046+00:00 app[web.1]:   Parameters: {"id"=>"2"}
2017-09-05T11:00:53.179611+00:00 app[web.1]:   Rendered event_instances/_hangout_button.html.erb (2.2ms)
2017-09-05T11:00:55.793712+00:00 app[web.1]:   Rendered event_instances/_hangout_button.html.erb (0.9ms)
2017-09-05T11:01:02.105955+00:00 app[web.1]: source=rack-timeout id=0d0de188-feb9-465b-b19a-25b81c4a2f54 wait=8ms timeout=20000ms service=20155ms state=timed_out
2017-09-05T11:01:02.315478+00:00 app[web.1]:   Rendered events/show.html.erb within layouts/application (20077.3ms)
2017-09-05T11:01:02.315640+00:00 app[web.1]: Request waited 8ms, then ran for longer than 20000ms
2017-09-05T11:01:02.315663+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
2017-09-05T11:01:02.315690+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
2017-09-05T11:01:02.315719+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
2017-09-05T11:01:02.315744+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2017-09-05T11:01:02.315766+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
2017-09-05T11:01:02.315788+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
2017-09-05T11:01:02.327899+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.7ms)
2017-09-05T11:01:02.328605+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.329931+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (0.8ms)
2017-09-05T11:01:02.417443+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (3.1ms)
2017-09-05T11:01:02.412796+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.4ms)
2017-09-05T11:01:02.417445+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.418093+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.2ms)
2017-09-05T11:01:02.419988+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (93.5ms)
2017-09-05T11:01:02.419804+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.418562+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.419386+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_data.text.erb (0.3ms)
2017-09-05T11:01:02.615753+00:00 app[web.1]: source=rack-timeout id=f39625fa-89af-4093-8c97-d249748cf412 wait=109ms timeout=20000ms service=20161ms state=timed_out
2017-09-05T11:01:02.621115+00:00 app[web.1]:   Rendered events/show.html.erb within layouts/application (18956.0ms)
2017-09-05T11:01:02.621366+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/time_with_zone.rb:391:in `year'
2017-09-05T11:01:02.621470+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/date_and_time/zones.rb:34:in `new'
2017-09-05T11:01:02.621504+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/date_and_time/zones.rb:34:in `time_with_zone'
2017-09-05T11:01:02.621406+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/time_with_zone.rb:391:in `transfer_time_values_to_utc_constructor'
2017-09-05T11:01:02.621328+00:00 app[web.1]: Request waited 109ms, then ran for longer than 20000ms
2017-09-05T11:01:02.621436+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/time_with_zone.rb:48:in `initialize'
2017-09-05T11:01:02.621538+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/date_and_time/zones.rb:24:in `in_time_zone'
2017-09-05T11:01:02.662978+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (1.0ms)
2017-09-05T11:01:02.663802+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2017-09-05T11:01:02.665891+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
2017-09-05T11:01:02.665387+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (0.8ms)
2017-09-05T11:01:02.672622+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (6.1ms)
2017-09-05T11:01:02.673173+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.678064+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (3.8ms)
2017-09-05T11:01:02.678569+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.679484+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_data.text.erb (0.4ms)
2017-09-05T11:01:02.679995+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
2017-09-05T11:01:02.680222+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (27.2ms)
2017-09-05T11:01:02.793771+00:00 app[web.1]: 
2017-09-05T11:01:02.793777+00:00 app[web.1]: Sent mail to info@agileventures.org (361.4ms)
2017-09-05T11:01:02.796244+00:00 app[web.1]:   Rendered static_pages/internal_error.html.erb within layouts/application (1.0ms)
2017-09-05T11:01:02.798425+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (1.0ms)
2017-09-05T11:01:02.799705+00:00 app[web.1]:   Rendered layouts/_head.html.erb (2.7ms)
2017-09-05T11:01:02.840017+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (0.3ms)
2017-09-05T11:01:02.840144+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (40.2ms)
2017-09-05T11:01:02.850045+00:00 app[web.1]:   Rendered layouts/_sponsors.html.erb (9.5ms)
2017-09-05T11:01:02.911354+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (51.4ms)
2017-09-05T11:01:02.911767+00:00 app[web.1]: Completed 500 Internal Server Error in 20950ms (Views: 32.8ms | ActiveRecord: 422.6ms)
2017-09-05T11:01:02.913632+00:00 app[web.1]: source=rack-timeout id=0d0de188-feb9-465b-b19a-25b81c4a2f54 wait=8ms timeout=20000ms service=20962ms state=completed

```

which seems to correspond to the action that I took ... looks like maybe the database getting stuck? fixed on a refresh ... says info@agileventures.org was emailed? but maybe that's inaccurate or another thread. 

So I need to work out here if airbrake is not supposed to catch 500 rails errors:

https://www.google.co.uk/search?q=why+does+airbrake+not+catch+rails+500+errors

or if we just have it configured incorrectly.

Either way if users are occasionally encountering these 500 errors I would like it tracked and to be offering them more apologies when it does ...

### LINKED ISSUE #1977: Better representation of upgrading subscription
Right now if a person is subscribed for a month or two as Premium and then upgrades to Premium Mob, then their subscription record type will be changed to premium mob rather than creating a new subscription for them and ending the old one.

So it will appear as they though had Premium Mob from the start.  Not ideal.

### PR DESCRIPTION
**Pull request by tansaku**
fixes #1429 
fixes #1977

### CODE REVIEW

File: spec/models/user_spec.rb [hunk 1]
```diff
@@ -493,14 +493,24 @@
     end
   end
 
-  context 'look up stripe id from subscription' do
-    let(:subscription) { mock_model(Subscription, save: true) }
-    before { allow(subscription).to receive(:[]=) }
+  context 'supporting current subscription' do
```
Comment (tansaku) [inline spec/models/user_spec.rb]: could re-do this with message chains rather than factory girl ...

Comment (tansaku) [reply spec/models/user_spec.rb]: gonna leave that to a refactoring ticket

Comment (tansaku) [reply spec/models/user_spec.rb]: see #2103
